### ISSUE TITLE
Defer statement is not highlighted

### ISSUE THREAD

**Issue by Airbus5717** [Tetralux/odin.vim#12]
this is kinda weird 
![image](https://user-images.githubusercontent.com/55999379/141528335-0fd657e6-397f-4f69-a46c-c2d191b20b42.png)

**Comment by Tetralux** [comment]
The problem being that `defer` isn't highlighted?

**Comment by Tetralux** [comment]
I cannot reproduce this on my end.
Can you double check that you have the latest version of odin.vim?
The latest commit as of this writing is ad3d7d40b21e022e05d17015c89f1bcaef68443f.

**Comment by Airbus5717** [comment]
i did a reinstall 
btw i am using Vundle pkg manager

**Comment by Tetralux** [comment]
Does it work now?

Apparently the defer keyword was being highlighted as an operator, which doesn't appear to affect my Vim/NVim due to the theme being used - but I'm guessing that it was affecting you.

**Comment by Airbus5717** [comment]
Yes its working now

**Comment by Tetralux** [comment]
Outstanding 🔥
