### ISSUE TITLE
Escaped quotations in strings are not properly highlighted

### ISSUE THREAD

**Issue by rivten** [Tetralux/odin.vim#17]
Hello !

If I write the string `"abcd\"efg\"hijk"`, then `efg` will not be highlighted as a string, even though it is escaped.

I might try to have a shot at it if I have the time.

**Comment by Tetralux** [comment]
Sorry this took so long to get to. I can't reproduce on latest commit. Are you still able to?

**Comment by Tetralux** [comment]
Appreciated. Welcome to the club! 😄
