### ISSUE TITLE
[BUG] It highlights text as being inside a string literal, even if the first " is inside '' (character literal)

### ISSUE THREAD

**Issue by MatiasPi** [Tetralux/odin.vim#3]
![nvim-qt_6wmBO99uW8](https://user-images.githubusercontent.com/11927498/63668218-deeeb900-c7ac-11e9-8fc7-c49f71afaa21.png)

Same problem if you escape the " with \ inside a string

**Comment by Tetralux** [comment]
Thanks for bringing this to my attention.
